esprit_back_office:
    resource: "@EspritBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /back

esprit_front_office:
    resource: "@EspritFrontOfficeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation
    
    
fos_user:    
    resource: "@FOSUserBundle/Resources/config/routing/all.xml" 


_imagine:
    resource: .
    type:     imagine
    

fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }